# Generated by Django 3.1.3 on 2020-11-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201121_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_approved',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
