# Generated by Django 3.1.3 on 2020-11-21 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20201121_1214'),
    ]

    operations = [
        migrations.DeleteModel(
            name='layout',
        ),
    ]
