# Generated by Django 3.1.3 on 2020-11-22 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cart',
        ),
    ]
